name: abaplint
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docsite/**'      
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docsite/**'

jobs:
  abaplint:
    name: abaplint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - uses: actions/checkout@v3
      - name: Run abaplint
        run: |
          npm -g install @abaplint/cli
          abaplint --format codeframe
