name: Test pages deployment

on:
  pull_request:
    branches:
      - master
    paths:
      - 'docsite/**'


jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: ./docsite
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: './docsite/package-lock.json'

      - name: Install dependencies
        run: npm ci
      - name: Test build website
        run: npm run build