name: transpile
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  transpile:
    name: transpile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
      - uses: actions/checkout@v2
      - name: Run abap transpiler
        run: |
          npm -g install @abaplint/transpiler
          abap_transpile abap_transpile.json
